# Generated by Django 5.2 on 2025-04-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='citation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-04 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='embedding',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='insights',
            field=models.TextField(blank=True, default='Insights not generated yet'),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='named_entities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
